version: 2.1

workflows:
  test-env-vars:
    jobs:
      - env-var:
          context: Testing-Env-Vars
          
      
jobs:
  env-var:
    docker:
      - image: cimg/base:2020.01
        environment:
          CIRCLE_JOB: ContainerEnvKey
    environment:
      CIRCLE_JOB: JobEnvKey
    steps:
      - checkout
      - run: 
          name: "override and echo built in environment variables"
          command: |
            # CIRCLE_JOB="StepCommand"
            echo $CIRCLE_JOB
          environment:
            CIRCLE_JOB: StepEnvKey
