version: 2.1

workflows:
  test-env-vars:
    jobs:
      - env-var
          #context: Testing-Env-Vars
          
      
jobs:
  env-var:
    docker:
      - image: cimg/base:2020.01
        environment:
          MY_ENV_VAR: ContainerEnvKey
    environment:
      CIRCLE_JOB: JobEnvKey
    steps:
      - checkout
      - run: 
          name: "override and echo built in environment variables"
          command: |
            #CIRCLE_JOB="StepCommand"
            #echo $CIRCLE_JOB
            echo $MY_ENV_VAR #print an env var that's specified in the context "Testing-Env-Vars" and project settings
          environment:
            CIRCLE_JOB: StepEnvKey
